# Generated by Django 5.1.4 on 2025-01-02 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0003_subscribepage_imageproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageproduct',
            name='landscape_image',
        ),
        migrations.RemoveField(
            model_name='imageproduct',
            name='portrait_image',
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_images', to='wagtailimages.image'),
        ),
    ]
