# Generated by Django 5.1.4 on 2025-01-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_imageproduct_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageproduct',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/products/'),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='image_orientation',
            field=models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10),
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2.34, max_digits=10),
            preserve_default=False,
        ),
    ]
