# Generated by Django 5.1.4 on 2025-01-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_imageproduct_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisticPrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/prints/')),
                ('image_orientation', models.CharField(choices=[('portrait', 'Portrait'), ('landscape', 'Landscape')], default='portrait', max_length=10)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('paper', models.CharField(blank=True, max_length=50)),
                ('mounting', models.CharField(blank=True, max_length=50)),
                ('payment_link_non_mounted', models.URLField(blank=True)),
                ('payment_link_mounted', models.URLField(blank=True)),
            ],
        ),
    ]
