# Generated by Django 5.1.4 on 2025-01-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_artisticprint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artisticprint',
            old_name='payment_link_mounted',
            new_name='payment_link',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='payment_link_non_mounted',
        ),
    ]
