# Generated by Django 5.1.4 on 2025-01-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_artisticprint_description_artisticprint_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisticprint',
            name='description',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='image_orientation',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='mounting',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='name',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='price',
        ),
        migrations.RemoveField(
            model_name='artisticprint',
            name='size',
        ),
    ]
