# Generated by Django 5.1.4 on 2025-01-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_remove_artisticprint_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArtisticPrint',
        ),
    ]
