# Generated by Django 3.0.3 on 2020-03-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='families',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='fashion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='indoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='outdoors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='portraits',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='weddings',
            field=models.BooleanField(default=False),
        ),
    ]
