# Generated by Django 3.0.3 on 2020-03-03 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200301_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
