# Generated by Django 3.0.3 on 2020-03-03 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallery', '0003_delete_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('full_size', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('weddings', models.BooleanField(default=False)),
                ('families', models.BooleanField(default=False)),
                ('indoors', models.BooleanField(default=False)),
                ('outdoors', models.BooleanField(default=False)),
                ('portraits', models.BooleanField(default=False)),
                ('fashion', models.BooleanField(default=False)),
            ],
        ),
    ]
