# Generated by Django 3.0.3 on 2020-04-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='social',
            field=models.CharField(default='', max_length=100),
        ),
    ]
