# Generated by Django 5.1.4 on 2025-01-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prints', '0002_delete_imageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisticprint',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
