# Generated by Django 3.0.3 on 2020-03-09 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('Gallery', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('Portfolio', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('Logo', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
