# Generated by Django 3.0.3 on 2020-04-05 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200308_2237'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Place', models.CharField(max_length=30)),
                ('Work', models.CharField(max_length=30)),
                ('Title', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('MainImg', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('SideImg', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('Facebook', models.CharField(max_length=60)),
                ('Instagram', models.CharField(max_length=60)),
            ],
        ),
    ]
