# Generated by Django 3.0.3 on 2020-04-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='Facebook',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Instagram',
            new_name='instagram',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='MainImg',
            new_name='mainImg',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='SideImg',
            new_name='sideImg',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='Work',
            new_name='work',
        ),
    ]
