# Generated by Django 3.0.3 on 2020-04-05 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200405_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
