# Generated by Django 3.0.3 on 2020-03-10 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('stripe', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('full', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('full2', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('full3', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
    ]
