# Generated by Django 3.0.3 on 2020-03-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='full',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full2',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full3',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='stripe',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
