# Generated by Django 3.0.3 on 2020-03-11 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200310_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='full',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='stripe',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
