# Generated by Django 3.0.3 on 2020-03-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200310_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
