# Generated by Django 3.0.3 on 2020-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_profiles_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='camera',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profiles',
            name='client',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='profiles',
            name='date',
            field=models.DateField(default='2020-03-10'),
        ),
        migrations.AddField(
            model_name='profiles',
            name='photographer',
            field=models.CharField(default='', max_length=30),
        ),
    ]
