# Generated by Django 3.0.3 on 2020-03-14 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_auto_20200313_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='date',
            field=models.DateField(default='2020-03-10'),
        ),
    ]
