# Generated by Django 3.0.3 on 2020-04-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200313_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='social',
            field=models.CharField(default='', max_length=100),
        ),
    ]
