# Generated by Django 3.0.3 on 2020-04-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_profiles_social'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='featurInfo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='profiles',
            name='featureImg',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
