# Generated by Django 3.0.3 on 2020-04-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20200404_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='featurInfo',
            new_name='featureInfo',
        ),
    ]
