# Generated by Django 3.0.3 on 2020-04-17 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_auto_20200404_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='full',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='full3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
